### ISSUE TITLE
6.6.2 As a System, I want to notify both users and the responsible authority in case of a data breach, so that I comply with GDPR’s breach notification requirements.

### ISSUE THREAD

**Issue by 1221289** [1221288/sem5pi-24-25-3dk63#30]
Acceptance Criteria:
- The system automatically detects potential data breaches and immediately notifies both the
affected users and the relevant GDPR authority.
- Breach notifications to users include:
 - Details of the breach (e.g., what data was compromised).
 - Steps being taken to mitigate the breach.
 - Recommendations for users (e.g., changing passwords, monitoring for suspicious activity).
- Notifications to the GDPR authority include detailed logs of the breach and actions taken.
- Breach notifications are sent within the legally required timeframe (e.g., 72 hours).
- The system logs all breach notifications and subsequent actions taken for auditing and
compliance purposes

**Comment by 1221288** [comment]
Article 33
